default: &default
  adapter: postgresql
  host: <%= ENV['MAJIN_DATABASE_HOST'] %>
  user: <%= ENV['MAJIN_DATABASE_USER'] %>
  pass: <%= ENV['MAJIN_DATABASE_PASS'] %>

development: 
  <<: *default
  database: majin_paste_devel


